"""Initial database schema

Revision ID: 98f1b5e4a5c8
Revises: 
Create Date: 2025-05-08 23:00:42.924708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f1b5e4a5c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_event_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sell_mode', sa.String(), nullable=True),
    sa.Column('organizer_company_id', sa.String(), nullable=True),
    sa.Column('ever_online', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_event_id', 'provider_name', name='uq_event_base_id_provider')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_event_ever_online', ['ever_online'], unique=False)
        batch_op.create_index('idx_event_last_seen_at', ['last_seen_at'], unique=False)
        batch_op.create_index('idx_event_provider_name', ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ever_online'), ['ever_online'], unique=False)

    op.create_table('event_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('base_plan_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sell_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sell_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sold_out', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_plan_id', 'provider_name', 'event_id', name='uq_plan_base_id_provider_event')
    )
    with op.batch_alter_table('event_plans', schema=None) as batch_op:
        batch_op.create_index('idx_event_plan_last_seen_at', ['last_seen_at'], unique=False)
        batch_op.create_index('idx_event_plan_provider_name', ['provider_name'], unique=False)
        batch_op.create_index('idx_event_plan_start_end_date', ['start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_plans_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_plans_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_plans_start_date'), ['start_date'], unique=False)

    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_plan_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_numbered', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_plan_id'], ['event_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'event_plan_id', name='uq_zone_base_id_plan')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index('idx_zone_last_seen_at', ['last_seen_at'], unique=False)
        batch_op.create_index('idx_zone_price', ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_event_plan_id'), ['event_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_event_plan_id'))
        batch_op.drop_index('idx_zone_price')
        batch_op.drop_index('idx_zone_last_seen_at')

    op.drop_table('zones')
    with op.batch_alter_table('event_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_plans_start_date'))
        batch_op.drop_index(batch_op.f('ix_event_plans_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_plans_end_date'))
        batch_op.drop_index('idx_event_plan_start_end_date')
        batch_op.drop_index('idx_event_plan_provider_name')
        batch_op.drop_index('idx_event_plan_last_seen_at')

    op.drop_table('event_plans')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_ever_online'))
        batch_op.drop_index('idx_event_provider_name')
        batch_op.drop_index('idx_event_last_seen_at')
        batch_op.drop_index('idx_event_ever_online')

    op.drop_table('events')
    # ### end Alembic commands ###
